name: Report PR Size Deltas

on:
  push:
    paths:
      - ".github/workflows/report-size-deltas.yml"
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
  repository_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@v1
        with:
          # Regex matching the names of the workflow artifacts created by the "Compile Examples" workflow
          sketches-reports-source: ^sketches-report-.+
